name: Unit Test

on:
  push:
    branches: [main]

jobs:
  unit-test:
    name: Compare Tests
    runs-on: ubuntu-latest
    env:
      ci: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests comparison between Jest and Vitest
        run: npm test
